### ISSUE TITLE
Color is deprecated, please switch to Colors

### ISSUE THREAD

**Issue by timholy** [davidssmith/DCEMRI.jl#10]
See https://github.com/JuliaLang/METADATA.jl/pull/3769; we're about to make Color uninstallable on julia 0.4.

**Comment by timholy** [comment]
Transition info: https://github.com/JuliaGraphics/Colors.jl#migrating-from-colorjl

**Comment by davidssmith** [comment]
Thanks for the heads up, Tim.  Should be fixed now.

**Comment by timholy** [comment]
Thanks!
