### ISSUE TITLE
Installing DCEMRI.jl failing

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#11]
Not sure, might be something on my end, though, looking for advice.

julia> Pkg.add("DCEMRI")
INFO: Initializing package repository /home/users/elijah/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection timed out

ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in run at ./process.jl:531
 in anonymous at pkg/dir.jl:52
 in cd at ./file.jl:22
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in add at pkg.jl:23

**Comment by davidssmith** [comment]
It looks like you are unable to connect to github.com.  Are you behind a firewall?

Can you try again?  If it doesn't work, try running 
```
traceroute github.com
```
and see where it hangs.

**Comment by elijahrockers** [comment]
Very likely my institution's firewall is the problem, but I have been able to pip install from git in the past.

traceroute to github.com (192.30.252.131), 30 hops max, 60 byte packets
 1  10.30.64.2 (10.30.64.2)  0.242 ms * *
 2  10.0.30.1 (10.0.30.1)  0.337 ms  0.408 ms  0.476 ms
 3  tmcfw-a-i.tmh.tmc.edu (10.0.0.1)  0.738 ms  0.726 ms  0.720 ms
 4  206.83.48.15 (206.83.48.15)  0.889 ms  0.873 ms  0.880 ms
 5  borderc2-gw-t3-1.chat.tmc.edu (192.31.88.237)  1.152 ms  0.986 ms  1.118 ms
 6  borderx1-gw-t2-3.chat.tmc.edu (192.31.88.85)  1.363 ms  1.081 ms  1.409 ms
 7  iah-edge-18.inet.qwest.net (63.145.96.57)  1.473 ms  1.647 ms  1.498 ms
 8  * * *
 9  * * *
10  ae-3-80.edge3.washington4.level3.net (4.69.149.146)  39.858 ms  39.874 ms  39.871 ms
11  ae-3-80.edge3.washington4.level3.net (4.69.149.146)  39.863 ms ae-2-70.edge3.washington4.level3.net (4.69.149.82)  39.974 ms  39.991 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by davidssmith** [comment]
What happens when you make a clean directory and run `git clone git@github.com:davidssmith/DCEMRI.jl.git`?

**Comment by elijahrockers** [comment]
elijah@picasso:~$ sudo git clone git@github.com:davidssmith/DCEMRI.jl.git
[sudo] password for elijah: 
Cloning into 'DCEMRI.jl'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by davidssmith** [comment]
The previous link required that you add your local ssh key to your Github account. You apparently have not done that. No worries.  Try this command instead: 

`git clone https://github.com/davidssmith/DCEMRI.jl.git`.

**Comment by elijahrockers** [comment]
Looks like the installation was successful. I'll see if I can get it to work now, thanks.

**Comment by davidssmith** [comment]
That command was to test your access to Github. It shouldn't have installed the package properly. To install the package in the correct location, you'll need to use the command `Pkg.add("DCEMRI")`.

**Comment by elijahrockers** [comment]
Oops. Previous command downloaded 144MB, guess I assumed that was the DCEMRI.jl software.

julia> Pkg.add("DCEMRI") gives the same error as before, connection timed out.

**Comment by davidssmith** [comment]
It seems other people are having this problem (https://github.com/JuliaLang/julia/issues/14762) because some firewalls may be blocking git. One workaround is to issue this command in the shell (not Julia):
```
git config --global url."https://".insteadOf git://
```

**Comment by davidssmith** [comment]
Also, this issue is related: https://github.com/JuliaLang/julia/issues/12583

**Comment by elijahrockers** [comment]
That seems to have done the trick. DCEMRI is now installed, thought I did get some errors toward the very end:

WARNING: Module BinDeps uuid did not match cache file
===============================[ ERROR: PyCall ]================================

LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading /home/users/elijah/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 12

================================================================================

==================================================================================================[ BUILD ERRORS ]===================================================================================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/users/elijah/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

=====================================================================================================================================================================================================================
INFO: Package database updated

julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using python (Python 2.7.3) at /usr/bin/python, libpython = /usr/lib/libpython2.7.so

Not sure if that fixed the problem or not.

**Comment by davidssmith** [comment]
Since you ran the validation, does this mean this issue is fixed?

**Comment by elijahrockers** [comment]
I would say yes, thank you
