### ISSUE TITLE
deprecated operators encountered during validation

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#12]
Not sure if this is affecting the calculations, but I got some warnings during validation.

Here they are, with repeat offenders omitted.

====

WARNING: ifloor(x) is deprecated, use floor(Integer,x) instead.
 in depwarn at deprecated.jl:73
 in ifloor at deprecated.jl:50
 in makeplots6 at /home/users/elijah/.julia/v0.4/DCEMRI/src/validate.jl:18

WARNING: [a] concatenation is deprecated; use collect(a) instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in makeplots6 at /home/users/elijah/.julia/v0.4/DCEMRI/src/validate.jl:18

WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in makeplots6 at /home/users/elijah/.julia/v0.4/DCEMRI/src/validate.jl:81

====

**Comment by davidssmith** [comment]
These are language changes made to Julia between versions 0.3 and 0.4-0.5, and they should not affect the results. They will need to be fixed eventually before the deprecations become errors, so I'll leave this issue open as a reminder.

**Comment by davidssmith** [comment]
Partially fixed by #13.
