### ISSUE TITLE
dimensionality of r1eff() in science.jl

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#18]
function currently only accepts 2D images.

consider using reshape instead of squeeze perhaps? also one for loop may have to be recursive to account for varying dimensionality

**Comment by davidssmith** [comment]
Good catch. `reshape` could be used in the way it is used in `ser`.

**Comment by elijahrockers** [comment]
Any chance you could take a look at
https://github.com/elijahrockers/DCEMRI.jl/issues/2
Not sure why I'm seeing this error in my fork

**Comment by elijahrockers** [comment]
fixed
