### ISSUE TITLE
version testing

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#19]
What's the best way to test different revisions of the code?

Like, how do I uninstall DCEMRI.jl and replace it with a different version?

**Comment by davidssmith** [comment]
You can use `Pkg.free("DCEMRI")` to remove the current package and 
```
Pkg.clone("https://github.com/davidssmith/DCEMRI.jl.git")
```
to get the latest master from this repo. If `Pkg.free()` doesn't work, just delete the `DCEMRI` directory under `.julia/v0.4`.

**Comment by elijahrockers** [comment]
got it
