### ISSUE TITLE
SER / Mask question

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#24]
When I run the software, with or without specifying a mask, my Ktrans map is almost all 0 except for a handful of voxels, hard to tell what area it is but I'm pretty sure it's not in any ROIs defined by the mask.

Any idea what the problem could be?

**Comment by davidssmith** [comment]
When you don't specific a mask, it uses a minimum SER value to determine which voxels to model. I believe the default is 2.  Maybe your data does not enhance very strongly?  Or maybe the SER calculation used in the code does work in your case?  Look at the output SER maps (SER.pdf) and see if those look believable.

**Comment by elijahrockers** [comment]
Yeah I looked at the SER map, I guess it looks fairly believable. It appears fairly split between which voxels are below 2 and which are above. I've tried playing with the cutoff too, but it seems I still get a very unpopulated Ktrans map either way (mostly zeros)

**Comment by elijahrockers** [comment]
To be honest I'm not exactly sure what is meant by "maybe my data does not enhance very strongly", I am not really familliar with SER

**Comment by elijahrockers** [comment]
perhaps I am specifying the mask incorrectly

**Comment by elijahrockers** [comment]
I'm seeing all the values of Ktrans are lying within the mask I specified, so I think the problem is somewhere else. I'm assuming the mask is recognized and used

**Comment by davidssmith** [comment]
The signal enhancement ratio (SER) is defined roughly as the max enhancement divided by the baseline. Only voxels that enhanced are receiving contrast agent, so only they are worth modeling.
