### ISSUE TITLE
TR units, seconds or ms?

### ISSUE THREAD

**Issue by elijahrockers** [davidssmith/DCEMRI.jl#25]
So, one thing I have tried to see if I can get reasonable Kt map is to change my TR value from .00314 seconds to 3.14 ms.

However the program asserts that 0 < TR < 1 "TR must be in units of ms"

So which is it, ms or s?

**Comment by davidssmith** [comment]
Should be `s`. The comment is likely outdated.

**Comment by elijahrockers** [comment]
I think I may have found my problem, possibly. My T1maps and DCE data were in ms, not s. I didn't realize because the entire array array was prefixed with a *10^3, and the individual elements appeared to be in seconds at a glance. Derp

Also I have fixed the comment in my fork.
