### ISSUE TITLE
v0.4 compatibility

### ISSUE THREAD

**Issue by davidssmith** [davidssmith/DCEMRI.jl#31]
The latest master is a huge improvement, but it is no longer `v0.4` compatible.  Not sure if we should just drop support for it, or use `Compat.jl` to try to make it work.

One I work this out, I'll issue a new release of the official package.

**Comment by notZaki** [comment]
Considering that Julia v0.5 is itself unmaintained now - see https://discourse.julialang.org/t/julia-0-5-is-now-officially-unmaintained/8169 - it would make sense for the package to drop support for the older versions.

**Comment by davidssmith** [comment]
Agreed.
