### ISSUE TITLE
QIBA datasets not found at specified address

### ISSUE THREAD

**Issue by vsaase** [davidssmith/DCEMRI.jl#46]
Hi,
could someone point me to the download location of the QIBA phantom DICOM data? The linked address in the README is out of date and also at https://qidw.rsna.org/ I cannot find anything like MRI Perfusion data.

thanks,
Victor

**Comment by vsaase** [comment]
sorry if I'm stupid, but is that the data in the test directory? then maybe the README is just misleading..

**Comment by davidssmith** [comment]
Everything you need should be downloaded when you install the package. The `test/` directory contains converted DICOM data already.

I agree that the README is misleading.

**Comment by notZaki** [comment]
Even though it's not necessary, the updated website for the QIBA phantoms is https://sites.duke.edu/dblab/qibacontent/

**Comment by davidssmith** [comment]
Thanks @notZaki
