### ISSUE TITLE
Allow use of Color > v0.3.7?

### ISSUE THREAD

**Issue by jiahao** [davidssmith/DCEMRI.jl#8]
Is there any particular reason to restrict the upper version of Color.jl?

**Comment by davidssmith** [comment]
There used to be a bug in the Color.jl that caused problems, but I believe recently it was fixed.  Have you tested the newest Color.jl version?

**Comment by jiahao** [comment]
For what it's worth, I have Color.jl checked out on master and the latest tagged version of DCEMRI (v0.1.1) and the tests pass.

**Comment by davidssmith** [comment]
I can confirm, so I have removed the restriction.
